export const developerData = [
  {
    id: '1',
    realName: '陈晓斌',
    avatar: '',
    className: '15广播电视工程2班',
    techDirection: '前端',
    followedNum: 42,
    tag: 'React;前端;大佬',
    isFollowed: true,
  },
  {
    id: '2',
    realName: '大白菜',
    avatar: '',
    className: '16广播电视工程2班',
    techDirection: '前端',
    followedNum: 1,
    tag: 'React;前端;菜鸡',
    isFollowed: true,
  },
  {
    id: '3',
    realName: '沈江峰',
    avatar: '',
    className: '15广播电视工程2班',
    techDirection: 'IOS',
    followedNum: 32,
    tag: '脱衣狂魔;小鸡短裤',
    isFollowed: true,
  },
  {
    id: '4',
    realName: '你傲哥',
    avatar: '',
    className: '15广播电视工程2班',
    techDirection: '全栈',
    followedNum: 8,
    tag: 'React;前端;大佬',
    isFollowed: false,
  },
  {
    id: '5',
    realName: '赵日天',
    avatar: '',
    className: '17电科1班',
    techDirection: '后端',
    followedNum: 8,
    tag: 'C#;.NET;话痨',
    isFollowed: false,
  },
  {
    id: '6',
    realName: '用户',
    avatar: '',
    className: '17电科1班',
    techDirection: '产品',
    followedNum: 23,
    tag: 'C#;aaa;aaaa;bbbbbbbbbbbbbbbbb..',
    isFollowed: false,
  },
  {
    id: '7',
    realName: '用户',
    avatar: '',
    className: '17电科1班',
    techDirection: '产品',
    followedNum: 23,
    tag: 'C#;aaa;aaaa;bb',
    isFollowed: false,
  },
  {
    id: '8',
    realName: '用户',
    avatar: '',
    className: '17电科1班',
    techDirection: '产品',
    followedNum: 23,
    tag: 'C#;aaa;aaaa;bb',
    isFollowed: false,
  },
  {
    id: '9',
    realName: '用户',
    avatar: '',
    className: '17电科1班',
    techDirection: '产品',
    followedNum: 23,
    tag: 'C#;aaa;aaaa;bb',
    isFollowed: false,
  },
  {
    id: '10',
    realName: '用户',
    avatar: '',
    className: '17电科1班',
    techDirection: '产品',
    followedNum: 23,
    tag: 'C#;aaa;aaaa;bb',
    isFollowed: false,
  },
  {
    id: '11',
    realName: '用户',
    avatar: '',
    className: '17电科1班',
    techDirection: '产品',
    followedNum: 23,
    tag: 'C#;aaa;aaaa;bb',
    isFollowed: false,
  },
  {
    id: '12',
    realName: '用户',
    avatar: '',
    className: '17电科1班',
    techDirection: '产品',
    followedNum: 23,
    tag: 'C#;aaa;aaaa;bb',
    isFollowed: false,
  },
  {
    id: '13',
    realName: '用户',
    avatar: '',
    className: '17电科1班',
    techDirection: '产品',
    followedNum: 23,
    tag: 'C#;aaa;aaaa;bb',
    isFollowed: false,
  },
];
export const articleData = [
  {
    id: '1',
    fileAddress: '/Annex/doc/React总结（1）.doc',
    fileName: 'React总结（1）',
    fileTag: 'React;个人总结;前端',
    url: null,
    content: '简单的聊一聊关于React的一些总结和看法',
    likeNum: 1,
    collectNum: 0,
    browseNum: 3,
    commentNum: 0,
    type: 'doc',
    remark: '',
    createUserName: '陈晓斌',
    createTime: '2019-01-14T17:46:28',
  },
  {
    id: '2',
    fileAddress: '/Annex/doc/React总结（2）.doc',
    fileName: 'React总结 -（2）',
    fileTag: 'React;前端',
    url: null,
    content: '今天我们来说一说React的艺术，希望对大家有帮助',
    likeNum: 1,
    collectNum: 0,
    browseNum: 3,
    commentNum: 0,
    type: 'doc',
    remark: '',
    createUserName: '陈晓斌',
    createTime: '2019-01-04T19:46:28',
  },
  {
    id: '3',
    fileAddress: '/Annex/doc/实习全书.doc',
    fileName: '如何正确的划水',
    fileTag: '划水;666;走位',
    url: null,
    content: '实习所有人面临的大问题，至今都让人不解，如何正确XXX',
    likeNum: 1,
    collectNum: 0,
    browseNum: 3,
    commentNum: 0,
    type: 'doc',
    remark: '',
    createUserName: '陆仁杰',
    createTime: '2019-02-24T15:26:28',
  },
];

export const techDirectionsType = [
  {
    value: '前端',
    key: '1',
  },
  {
    value: '后端',
    key: '2',
  },
  {
    value: 'IOS',
    key: '3',
  },
  {
    value: 'Andriod',
    key: '4',
  },
  {
    value: '美工',
    key: '5',
  },
  {
    value: '产品',
    key: '6',
  },
  {
    value: 'AI智能',
    key: '7',
  },
  {
    value: 'VR世界',
    key: '8',
  },
];
